title: AtomicSponge
description: >-
  My website
url: "https://atomicsponge.wtfsystems.net"
github_username:  AtomicSponge

lsi: false
safe: true
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
highlighter: rouge

include: [docs]
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - CNAME
  - LICENSE.md
  - README.md